
# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
collections:
  projects:
    layout: content
    output: true

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
